name: Release

on:
  push:
    tags:
      - '**'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # The COMMIT_KEY secret contains a private SSH key. The associated public key
          # has been added as a deploy key in the GitHub project. See:
          # https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys
          # This is necessary to make commits done by github-actions able to trigger
          # further github-actions. See: https://stackoverflow.com/q/60418323/3018229.
          ssh-key: "${{secrets.COMMIT_KEY}}"

      - name: Create Package
        run: tar -czf forgit-${{github.ref_name}}.tar.gz --exclude LICENSE --exclude README.md *

      - name: Generate Changelog and Tag
        id: changelog
        run: .github/scripts/changelog.sh > CHANGELOG.md
        env:
          REPO_URL: ${{github.server_url}}/${{github.repository}}
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: steps.changelog.outcome == 'success'
        with:
          body_path: CHANGELOG.md
          files: forgit-${{github.ref_name}}.tar.gz
